apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-0
  labels:
    app: nginx-pv
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/ng-0/datadir
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-1
  labels:
    app: nginx-pv
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/ng-1/datadir
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-2
  labels:
    app: nginx-pv
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pods/ng-2/datadir
    type: DirectoryOrCreate
