apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-nginx-sts-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nginx-pv
      podindex: "0"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-nginx-sts-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nginx-pv
      podindex: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-nginx-sts-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nginx-pv
      podindex: "2"
